[project]
name = "uv-django"
version = "0.1.0"
description = "Django Project"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django>=5.2.8",
    "gunicorn>=23.0.0",
    "python-dotenv>=1.2.1",
]
